use socket with context manager while checking reachability (#1070)
we check for server pod reachability by opening a socket connection and
when pod is not reachable due to a programming mistake we always hit an
exception w/o making any progress while closing sock.

There seems to be underlying bug as well, as we are returning from try
w/o closing sock and so when pod is reachable we aren't hitting the issue.

```
File "/kadalu/kadalulib.py", line 106, in is_server_pod_reachable
sock.close()
UnboundLocalError: local variable 'sock' referenced before assignment
[2024-05-22 06:57:45,569] INFO [kadalulib - 432:monitor_proc] - Restarted Process name=csi
```

ref: #1069

Signed-off-by: Leela Venkaiah G <leelavg@thoughtexpo.com>